### ISSUE TITLE
Sire fails to compile with python 3.12

### ISSUE THREAD

**Issue by fjclark** [OpenBioSim/sire#147]
**Describe the bug**
I am unable to compile the latest devel version of sire. The final section of the error message is unhelpful:
```
cd /export/users/finlayclark/software/sire-openbiosim/build/sire-boresch_sire-boresch_wrapper/Mol && /export/users/finlayclark/miniconda3/envs/sire-boresch/bin/cmake -E cmake_symlink_library _Mol.so.2024.1.0 _Mol.so.2024 _Mol.so                                                                                                  gmake[2]: Leaving directory '/export/users/finlayclark/software/sire-openbiosim/build/sire-boresch_sire-boresch_wrapper'                                           [ 90%] Built target Mol                                                                                                                                            gmake[1]: Leaving directory '/export/users/finlayclark/software/sire-openbiosim/build/sire-boresch_sire-boresch_wrapper'                                           gmake: *** [Makefile:136: all] Error 2                                                                                                                             SOMETHING WENT WRONG WHEN COMPILING THE WRAPPERS! 
```
and I am unable to find any error messages further up in the output.

**To Reproduce**
I have followed the steps given on github to compile.

**Cause**

python<3.12 was not specified in the requirements files, so the initial python 3.11 was being updated to 3.12 when `python setup.py install` was run.

**(please complete the following information):**
 - OS: Ubuntu 20.04
 - Version of Python: Intially 3.11, unintentionally updated to 3.12
 - Version of sire:  latest `dev` release
 - I confirm that I have checked this bug still exists in the latest released version of sire: yes

**Comment by chryswoods** [comment]
Thanks - could you install adding the '--install-bss-deps' option? This will bring in BioSimSpace's dependencies, which aren't all available for 3.12 at the moment (although I haven't checked this for a couple of weeks).

I'll look into the compiler error - this suggests that the base sire dependencies are available for 3.12 and there is something in sire that needs fixing, so that we are ready for 3.12 once BioSimSpace's dependencies are available.

**Comment by fjclark** [comment]
Thanks. I can confirm that adding '--install-bss-deps' avoids python being updated to 3.12 and allows sire to compile.

Thanks very much. Here's a more readable version of the end of the error:
```
[ 86%] Linking CXX shared library _Mol.so
cd /home/finlayclark/software/devel/sire/build/test_1_test_1_wrapper/Mol && /home/finlayclark/anaconda3/envs/mamba/envs/test_1/bin/cmake -E cmake_link_script CMakeFiles/Mol.dir/link.txt --verbose=1
/home/finlayclark/anaconda3/envs/mamba/envs/test_1/bin/x86_64-conda-linux-gnu-g++ -fPIC -Wall -Wno-attributes -pipe -DSIRE_ALWAYS_INLINE=inline -Wno-strict-aliasing -DSIRE_VISIBILITY_AVAILABLE -fvisibility=hidden -fvisibility-inlines-hidden  -std=c++17 -DSIRE_HAS_CPP_17 -DSIRE_HAS_CPP_14 -DSIRE_HAS_CPP_1Y -DSIRE_HAS_CPP_11 -Os  -w   -rdynamic -Wl,--no-undefined -lpthread -shared -Wl,-soname,_Mol.so.2024 -o _Mol.so.2024.1.0 CMakeFiles/Mol.dir/_Mol.main.cpp.o CMakeFiles/Mol.dir/AbsFromMass.pypp.cpp.o CMakeFiles/Mol.dir/AbsFromNumber.pypp.cpp.o CMakeFiles/Mol.dir/AmberParameters.pypp.cpp.o CMakeFiles/Mol.dir/AngleID.pypp.cpp.o CMakeFiles/Mol.dir/AnglePerturbation.pypp.cpp.o CMakeFiles/Mol.dir/Atom.pypp.cpp.o CMakeFiles/Mol.dir/AtomBeads.pypp.cpp.o CMakeFiles/Mol.dir/AtomCharges.pypp.cpp.o CMakeFiles/Mol.dir/AtomChiralities.pypp.cpp.o CMakeFiles/Mol.dir/AtomCoords.pypp.cpp.o CMakeFiles/Mol.dir/AtomCutting.pypp.cpp.o CMakeFiles/Mol.dir/AtomDoubleArrayProperty.pypp.cpp.o CMakeFiles/Mol.dir/AtomEditor.pypp.cpp.o CMakeFiles/Mol.dir/AtomEditorBase.pypp.cpp.o CMakeFiles/Mol.dir/AtomElements.pypp.cpp.o CMakeFiles/Mol.dir/AtomEnergies.pypp.cpp.o CMakeFiles/Mol.dir/AtomFloatProperty.pypp.cpp.o CMakeFiles/Mol.dir/AtomForces.pypp.cpp.o CMakeFiles/Mol.dir/AtomHybridizations.pypp.cpp.o CMakeFiles/Mol.dir/AtomID.pypp.cpp.o CMakeFiles/Mol.dir/AtomIDMatcher.pypp.cpp.o CMakeFiles/Mol.dir/AtomIdx.pypp.cpp.o CMakeFiles/Mol.dir/AtomIdxMatcher.pypp.cpp.o CMakeFiles/Mol.dir/AtomIntProperty.pypp.cpp.o CMakeFiles/Mol.dir/AtomIntegerArrayProperty.pypp.cpp.o CMakeFiles/Mol.dir/AtomMCSMatcher.pypp.cpp.o CMakeFiles/Mol.dir/AtomMapping.pypp.cpp.o CMakeFiles/Mol.dir/AtomMasses.pypp.cpp.o CMakeFiles/Mol.dir/AtomMatch.pypp.cpp.o CMakeFiles/Mol.dir/AtomMatchInverter.pypp.cpp.o CMakeFiles/Mol.dir/AtomMatchM.pypp.cpp.o CMakeFiles/Mol.dir/AtomMatcher.pypp.cpp.o CMakeFiles/Mol.dir/AtomMultiMatcher.pypp.cpp.o CMakeFiles/Mol.dir/AtomName.pypp.cpp.o CMakeFiles/Mol.dir/AtomNameMatcher.pypp.cpp.o CMakeFiles/Mol.dir/AtomNum.pypp.cpp.o CMakeFiles/Mol.dir/AtomPolarisabilities.pypp.cpp.o CMakeFiles/Mol.dir/AtomProp.pypp.cpp.o CMakeFiles/Mol.dir/AtomPropertyList.pypp.cpp.o CMakeFiles/Mol.dir/AtomPropertyProperty.pypp.cpp.o CMakeFiles/Mol.dir/AtomRadicals.pypp.cpp.o CMakeFiles/Mol.dir/AtomRadii.pypp.cpp.o CMakeFiles/Mol.dir/AtomResultMatcher.pypp.cpp.o CMakeFiles/Mol.dir/AtomSelection.pypp.cpp.o CMakeFiles/Mol.dir/AtomStringArrayProperty.pypp.cpp.o CMakeFiles/Mol.dir/AtomStringProperty.pypp.cpp.o CMakeFiles/Mol.dir/AtomStructureEditor.pypp.cpp.o CMakeFiles/Mol.dir/AtomVariantProperty.pypp.cpp.o CMakeFiles/Mol.dir/AtomVelocities.pypp.cpp.o CMakeFiles/Mol.dir/AtomsIn_CGID_.pypp.cpp.o CMakeFiles/Mol.dir/AtomsIn_ChainID_.pypp.cpp.o CMakeFiles/Mol.dir/AtomsIn_ResID_.pypp.cpp.o CMakeFiles/Mol.dir/AtomsIn_SegID_.pypp.cpp.o CMakeFiles/Mol.dir/Bead.pypp.cpp.o CMakeFiles/Mol.dir/BeadEditor.pypp.cpp.o CMakeFiles/Mol.dir/BeadEditorBase.pypp.cpp.o CMakeFiles/Mol.dir/BeadFloatProperty.pypp.cpp.o CMakeFiles/Mol.dir/BeadID.pypp.cpp.o CMakeFiles/Mol.dir/BeadIdx.pypp.cpp.o CMakeFiles/Mol.dir/BeadIntProperty.pypp.cpp.o CMakeFiles/Mol.dir/BeadNum.pypp.cpp.o CMakeFiles/Mol.dir/BeadProp.pypp.cpp.o CMakeFiles/Mol.dir/BeadPropertyProperty.pypp.cpp.o CMakeFiles/Mol.dir/BeadStringProperty.pypp.cpp.o CMakeFiles/Mol.dir/BeadVariantProperty.pypp.cpp.o CMakeFiles/Mol.dir/Beading.pypp.cpp.o CMakeFiles/Mol.dir/Beads.pypp.cpp.o CMakeFiles/Mol.dir/BondHunter.pypp.cpp.o CMakeFiles/Mol.dir/BondID.pypp.cpp.o CMakeFiles/Mol.dir/BondOrder.pypp.cpp.o CMakeFiles/Mol.dir/BondPerturbation.pypp.cpp.o CMakeFiles/Mol.dir/CGAtomID.pypp.cpp.o CMakeFiles/Mol.dir/CGAtomIdx.pypp.cpp.o CMakeFiles/Mol.dir/CGChainID.pypp.cpp.o CMakeFiles/Mol.dir/CGEditor.pypp.cpp.o CMakeFiles/Mol.dir/CGEditorBase.pypp.cpp.o CMakeFiles/Mol.dir/CGFloatProperty.pypp.cpp.o CMakeFiles/Mol.dir/CGID.pypp.cpp.o CMakeFiles/Mol.dir/CGIdx.pypp.cpp.o CMakeFiles/Mol.dir/CGIntProperty.pypp.cpp.o CMakeFiles/Mol.dir/CGName.pypp.cpp.o CMakeFiles/Mol.dir/CGProp.pypp.cpp.o CMakeFiles/Mol.dir/CGPropertyProperty.pypp.cpp.o CMakeFiles/Mol.dir/CGResID.pypp.cpp.o CMakeFiles/Mol.dir/CGStringProperty.pypp.cpp.o CMakeFiles/Mol.dir/CGStructureEditor.pypp.cpp.o CMakeFiles/Mol.dir/CGVariantProperty.pypp.cpp.o CMakeFiles/Mol.dir/CGsWithAtoms.pypp.cpp.o CMakeFiles/Mol.dir/Chain.pypp.cpp.o CMakeFiles/Mol.dir/ChainAtomID.pypp.cpp.o CMakeFiles/Mol.dir/ChainEditor.pypp.cpp.o CMakeFiles/Mol.dir/ChainEditorBase.pypp.cpp.o CMakeFiles/Mol.dir/ChainFloatProperty.pypp.cpp.o CMakeFiles/Mol.dir/ChainID.pypp.cpp.o CMakeFiles/Mol.dir/ChainIdx.pypp.cpp.o CMakeFiles/Mol.dir/ChainIntProperty.pypp.cpp.o CMakeFiles/Mol.dir/ChainName.pypp.cpp.o CMakeFiles/Mol.dir/ChainProp.pypp.cpp.o CMakeFiles/Mol.dir/ChainPropertyProperty.pypp.cpp.o CMakeFiles/Mol.dir/ChainResID.pypp.cpp.o CMakeFiles/Mol.dir/ChainStringProperty.pypp.cpp.o CMakeFiles/Mol.dir/ChainStructureEditor.pypp.cpp.o CMakeFiles/Mol.dir/ChainVariantProperty.pypp.cpp.o CMakeFiles/Mol.dir/ChainsWithAtoms.pypp.cpp.o CMakeFiles/Mol.dir/ChainsWithRes.pypp.cpp.o CMakeFiles/Mol.dir/ChargePerturbation.pypp.cpp.o CMakeFiles/Mol.dir/ChemicalBondHunter.pypp.cpp.o CMakeFiles/Mol.dir/Chirality.pypp.cpp.o CMakeFiles/Mol.dir/Connectivity.pypp.cpp.o CMakeFiles/Mol.dir/ConnectivityBase.pypp.cpp.o CMakeFiles/Mol.dir/ConnectivityEditor.pypp.cpp.o CMakeFiles/Mol.dir/CovalentBondHunter.pypp.cpp.o CMakeFiles/Mol.dir/CovalentBondHunterParameters.pypp.cpp.o CMakeFiles/Mol.dir/CutGroup.pypp.cpp.o CMakeFiles/Mol.dir/CuttingFunction.pypp.cpp.o CMakeFiles/Mol.dir/DihedralID.pypp.cpp.o CMakeFiles/Mol.dir/DihedralPerturbation.pypp.cpp.o CMakeFiles/Mol.dir/Element.pypp.cpp.o CMakeFiles/Mol.dir/Evaluator.pypp.cpp.o CMakeFiles/Mol.dir/EvaluatorM.pypp.cpp.o CMakeFiles/Mol.dir/Force3D.pypp.cpp.o CMakeFiles/Mol.dir/Frame.pypp.cpp.o CMakeFiles/Mol.dir/FrameTransform.pypp.cpp.o CMakeFiles/Mol.dir/GeometryPerturbation.pypp.cpp.o CMakeFiles/Mol.dir/GeometryPerturbations.pypp.cpp.o CMakeFiles/Mol.dir/GroupAtomIDBase.pypp.cpp.o CMakeFiles/Mol.dir/Hybridization.pypp.cpp.o CMakeFiles/Mol.dir/IDAndSet_AtomID_.pypp.cpp.o CMakeFiles/Mol.dir/IDAndSet_CGID_.pypp.cpp.o CMakeFiles/Mol.dir/IDAndSet_ChainID_.pypp.cpp.o CMakeFiles/Mol.dir/IDAndSet_MGID_.pypp.cpp.o CMakeFiles/Mol.dir/IDAndSet_MolID_.pypp.cpp.o CMakeFiles/Mol.dir/IDAndSet_ResID_.pypp.cpp.o CMakeFiles/Mol.dir/IDAndSet_SegID_.pypp.cpp.o CMakeFiles/Mol.dir/IDOrSet_AtomID_.pypp.cpp.o CMakeFiles/Mol.dir/IDOrSet_CGID_.pypp.cpp.o CMakeFiles/Mol.dir/IDOrSet_ChainID_.pypp.cpp.o CMakeFiles/Mol.dir/IDOrSet_MGID_.pypp.cpp.o CMakeFiles/Mol.dir/IDOrSet_MolID_.pypp.cpp.o CMakeFiles/Mol.dir/IDOrSet_ResID_.pypp.cpp.o CMakeFiles/Mol.dir/IDOrSet_SegID_.pypp.cpp.o CMakeFiles/Mol.dir/ImproperID.pypp.cpp.o CMakeFiles/Mol.dir/InvertMatch_AtomID_.pypp.cpp.o CMakeFiles/Mol.dir/InvertMatch_CGID_.pypp.cpp.o CMakeFiles/Mol.dir/InvertMatch_ChainID_.pypp.cpp.o CMakeFiles/Mol.dir/InvertMatch_ResID_.pypp.cpp.o CMakeFiles/Mol.dir/InvertMatch_SegID_.pypp.cpp.o CMakeFiles/Mol.dir/MGID.pypp.cpp.o CMakeFiles/Mol.dir/MGIDsAndMaps.pypp.cpp.o CMakeFiles/Mol.dir/MGIdx.pypp.cpp.o CMakeFiles/Mol.dir/MGName.pypp.cpp.o CMakeFiles/Mol.dir/MGNum.pypp.cpp.o CMakeFiles/Mol.dir/MatchAll_AtomID_.pypp.cpp.o CMakeFiles/Mol.dir/MatchAll_CGID_.pypp.cpp.o CMakeFiles/Mol.dir/MatchAll_ChainID_.pypp.cpp.o CMakeFiles/Mol.dir/MatchAll_ResID_.pypp.cpp.o CMakeFiles/Mol.dir/MatchAll_SegID_.pypp.cpp.o CMakeFiles/Mol.dir/MolAtomID.pypp.cpp.o CMakeFiles/Mol.dir/MolEditor.pypp.cpp.o CMakeFiles/Mol.dir/MolEditorBase.pypp.cpp.o CMakeFiles/Mol.dir/MolGroupsBase.pypp.cpp.o CMakeFiles/Mol.dir/MolID.pypp.cpp.o CMakeFiles/Mol.dir/MolIdx.pypp.cpp.o CMakeFiles/Mol.dir/MolInfo.pypp.cpp.o CMakeFiles/Mol.dir/MolName.pypp.cpp.o CMakeFiles/Mol.dir/MolNum.pypp.cpp.o CMakeFiles/Mol.dir/MolResID.pypp.cpp.o CMakeFiles/Mol.dir/MolResNum.pypp.cpp.o CMakeFiles/Mol.dir/MolStructureEditor.pypp.cpp.o CMakeFiles/Mol.dir/MolViewProperty.pypp.cpp.o CMakeFiles/Mol.dir/MolWithResID.pypp.cpp.o CMakeFiles/Mol.dir/Molecule.pypp.cpp.o CMakeFiles/Mol.dir/MoleculeBeading.pypp.cpp.o CMakeFiles/Mol.dir/MoleculeGroup.pypp.cpp.o CMakeFiles/Mol.dir/MoleculeGroups.pypp.cpp.o CMakeFiles/Mol.dir/MoleculeInfo.pypp.cpp.o CMakeFiles/Mol.dir/MoleculeProperty.pypp.cpp.o CMakeFiles/Mol.dir/MoleculeView.pypp.cpp.o CMakeFiles/Mol.dir/Molecules.pypp.cpp.o CMakeFiles/Mol.dir/MoverBase.pypp.cpp.o CMakeFiles/Mol.dir/Mover_Atom_.pypp.cpp.o CMakeFiles/Mol.dir/Mover_Bead_.pypp.cpp.o CMakeFiles/Mol.dir/Mover_Beads_.pypp.cpp.o CMakeFiles/Mol.dir/Mover_Chain_.pypp.cpp.o CMakeFiles/Mol.dir/Mover_CutGroup_.pypp.cpp.o CMakeFiles/Mol.dir/Mover_Molecule_.pypp.cpp.o CMakeFiles/Mol.dir/Mover_PartialMolecule_.pypp.cpp.o CMakeFiles/Mol.dir/Mover_Residue_.pypp.cpp.o CMakeFiles/Mol.dir/Mover_Segment_.pypp.cpp.o CMakeFiles/Mol.dir/Mover_Selector_Atom_.pypp.cpp.o CMakeFiles/Mol.dir/Mover_Selector_Chain_.pypp.cpp.o CMakeFiles/Mol.dir/Mover_Selector_CutGroup_.pypp.cpp.o CMakeFiles/Mol.dir/Mover_Selector_Residue_.pypp.cpp.o CMakeFiles/Mol.dir/Mover_Selector_Segment_.pypp.cpp.o CMakeFiles/Mol.dir/NullBeading.pypp.cpp.o CMakeFiles/Mol.dir/NullBondHunter.pypp.cpp.o CMakeFiles/Mol.dir/NullGeometryPerturbation.pypp.cpp.o CMakeFiles/Mol.dir/NullPerturbation.pypp.cpp.o CMakeFiles/Mol.dir/PartialMolecule.pypp.cpp.o CMakeFiles/Mol.dir/Perturbation.pypp.cpp.o CMakeFiles/Mol.dir/PerturbationSymbols.pypp.cpp.o CMakeFiles/Mol.dir/Perturbations.pypp.cpp.o CMakeFiles/Mol.dir/Radical.pypp.cpp.o CMakeFiles/Mol.dir/RelFromMass.pypp.cpp.o CMakeFiles/Mol.dir/RelFromNumber.pypp.cpp.o CMakeFiles/Mol.dir/ResAtomID.pypp.cpp.o CMakeFiles/Mol.dir/ResEditor.pypp.cpp.o CMakeFiles/Mol.dir/ResEditorBase.pypp.cpp.o CMakeFiles/Mol.dir/ResFloatProperty.pypp.cpp.o CMakeFiles/Mol.dir/ResID.pypp.cpp.o CMakeFiles/Mol.dir/ResIdx.pypp.cpp.o CMakeFiles/Mol.dir/ResIdxAtomCoordMatcher.pypp.cpp.o CMakeFiles/Mol.dir/ResIdxAtomMCSMatcher.pypp.cpp.o CMakeFiles/Mol.dir/ResIdxAtomNameMatcher.pypp.cpp.o CMakeFiles/Mol.dir/ResIn_ChainID_.pypp.cpp.o CMakeFiles/Mol.dir/ResIntProperty.pypp.cpp.o CMakeFiles/Mol.dir/ResName.pypp.cpp.o CMakeFiles/Mol.dir/ResNum.pypp.cpp.o CMakeFiles/Mol.dir/ResNumAtomNameMatcher.pypp.cpp.o CMakeFiles/Mol.dir/ResProp.pypp.cpp.o CMakeFiles/Mol.dir/ResPropertyProperty.pypp.cpp.o CMakeFiles/Mol.dir/ResStringProperty.pypp.cpp.o CMakeFiles/Mol.dir/ResStructureEditor.pypp.cpp.o CMakeFiles/Mol.dir/ResVariantProperty.pypp.cpp.o CMakeFiles/Mol.dir/ResWithAtoms.pypp.cpp.o CMakeFiles/Mol.dir/Residue.pypp.cpp.o CMakeFiles/Mol.dir/ResidueBeading.pypp.cpp.o CMakeFiles/Mol.dir/ResidueCutting.pypp.cpp.o CMakeFiles/Mol.dir/SegAtomID.pypp.cpp.o CMakeFiles/Mol.dir/SegCGID.pypp.cpp.o CMakeFiles/Mol.dir/SegChainID.pypp.cpp.o CMakeFiles/Mol.dir/SegEditor.pypp.cpp.o CMakeFiles/Mol.dir/SegEditorBase.pypp.cpp.o CMakeFiles/Mol.dir/SegFloatProperty.pypp.cpp.o CMakeFiles/Mol.dir/SegID.pypp.cpp.o CMakeFiles/Mol.dir/SegIdx.pypp.cpp.o CMakeFiles/Mol.dir/SegIntProperty.pypp.cpp.o CMakeFiles/Mol.dir/SegName.pypp.cpp.o CMakeFiles/Mol.dir/SegProp.pypp.cpp.o CMakeFiles/Mol.dir/SegPropertyProperty.pypp.cpp.o CMakeFiles/Mol.dir/SegResID.pypp.cpp.o CMakeFiles/Mol.dir/SegStringProperty.pypp.cpp.o CMakeFiles/Mol.dir/SegStructureEditor.pypp.cpp.o CMakeFiles/Mol.dir/SegVariantProperty.pypp.cpp.o CMakeFiles/Mol.dir/Segment.pypp.cpp.o CMakeFiles/Mol.dir/SegsWithAtoms.pypp.cpp.o CMakeFiles/Mol.dir/Select.pypp.cpp.o CMakeFiles/Mol.dir/SelectResult.pypp.cpp.o CMakeFiles/Mol.dir/SelectResultMover.pypp.cpp.o CMakeFiles/Mol.dir/SelectorM_Atom_.pypp.cpp.o CMakeFiles/Mol.dir/SelectorM_Chain_.pypp.cpp.o CMakeFiles/Mol.dir/SelectorM_CutGroup_.pypp.cpp.o CMakeFiles/Mol.dir/SelectorM_Residue_.pypp.cpp.o CMakeFiles/Mol.dir/SelectorM_Segment_.pypp.cpp.o CMakeFiles/Mol.dir/SelectorMol.pypp.cpp.o CMakeFiles/Mol.dir/Selector_Atom_.pypp.cpp.o CMakeFiles/Mol.dir/Selector_Chain_.pypp.cpp.o CMakeFiles/Mol.dir/Selector_CutGroup_.pypp.cpp.o CMakeFiles/Mol.dir/Selector_Residue_.pypp.cpp.o CMakeFiles/Mol.dir/Selector_Segment_.pypp.cpp.o CMakeFiles/Mol.dir/SpecifyMol.pypp.cpp.o CMakeFiles/Mol.dir/Specify_AtomID_.pypp.cpp.o CMakeFiles/Mol.dir/Specify_CGID_.pypp.cpp.o CMakeFiles/Mol.dir/Specify_ChainID_.pypp.cpp.o CMakeFiles/Mol.dir/Specify_MGID_.pypp.cpp.o CMakeFiles/Mol.dir/Specify_ResID_.pypp.cpp.o CMakeFiles/Mol.dir/Specify_SegID_.pypp.cpp.o CMakeFiles/Mol.dir/Stereochemistry.pypp.cpp.o CMakeFiles/Mol.dir/Trajectory.pypp.cpp.o CMakeFiles/Mol.dir/TrajectoryAligner.pypp.cpp.o CMakeFiles/Mol.dir/UserBeading.pypp.cpp.o CMakeFiles/Mol.dir/Velocity3D.pypp.cpp.o CMakeFiles/Mol.dir/VolumeMap.pypp.cpp.o CMakeFiles/Mol.dir/WeightFunction.pypp.cpp.o CMakeFiles/Mol.dir/Within.pypp.cpp.o CMakeFiles/Mol.dir/_Mol_free_functions.pypp.cpp.o CMakeFiles/Mol.dir/SireMol_containers.cpp.o CMakeFiles/Mol.dir/SireMol_properties.cpp.o CMakeFiles/Mol.dir/SireMol_registrars.cpp.o  -Wl,-rpath,/home/finlayclark/software/devel/sire/build/test_1_test_1_wrapper/Helpers:/home/finlayclark/anaconda3/envs/mamba/envs/test_1/pkgs/sire-2024.1.0/lib: ../Helpers/libSirePython.so.2024.1.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/pkgs/sire-2024.1.0/lib/libSireMM.so.2024.1.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/lib/libboost_python312.so.1.82.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/pkgs/sire-2024.1.0/lib/libSireCluster.so.2024.1.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/lib/libpython3.12.so /home/finlayclark/anaconda3/envs/mamba/envs/test_1/pkgs/sire-2024.1.0/lib/libSireFF.so.2024.1.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/pkgs/sire-2024.1.0/lib/libSireMol.so.2024.1.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/pkgs/sire-2024.1.0/lib/libSireVol.so.2024.1.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/pkgs/sire-2024.1.0/lib/libSireCAS.so.2024.1.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/pkgs/sire-2024.1.0/lib/libSireMaths.so.2024.1.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/pkgs/sire-2024.1.0/lib/libSireBase.so.2024.1.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/pkgs/sire-2024.1.0/lib/libSireID.so.2024.1.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/pkgs/sire-2024.1.0/lib/libSireUnits.so.2024.1.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/pkgs/sire-2024.1.0/lib/libSireStream.so.2024.1.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/pkgs/sire-2024.1.0/lib/libSireError.so.2024.1.0 /home/finlayclark/anaconda3/envs/mamba/envs/test_1/lib/libQt5Core.so.5.15.8 -L/home/finlayclark/anaconda3/envs/mamba/envs/test_1/lib -lgsl -lm /home/finlayclark/anaconda3/envs/mamba/envs/test_1/lib/libtbb.so /home/finlayclark/anaconda3/envs/mamba/envs/test_1/lib/libtbbmalloc.so
cd /home/finlayclark/software/devel/sire/build/test_1_test_1_wrapper/Mol && /home/finlayclark/anaconda3/envs/mamba/envs/test_1/bin/cmake -E cmake_symlink_library _Mol.so.2024.1.0 _Mol.so.2024 _Mol.so
make[2]: Leaving directory '/home/finlayclark/software/devel/sire/build/test_1_test_1_wrapper'
[ 86%] Built target Mol
make[1]: Leaving directory '/home/finlayclark/software/devel/sire/build/test_1_test_1_wrapper'
SOMETHING WENT WRONG WHEN COMPILING THE WRAPPERS!
```

**Comment by chryswoods** [comment]
No problem - your report is really useful because it does point to some work we need to do to make sure sire works with 3.12. It's a useful "early warning system" ;-)

I'll leave this issue open and will rename it so it can be tagged as something that needs fixing for 2024.1.0

**Comment by chryswoods** [comment]
I can confirm that I can reproduce this. It is an error relating to part of the Python C API that was removed in 3.12. The error message is a long way up - it is here;

```
/home/parallels/Coding/sire/wrapper/Qt/autoconvert_QChar.cpp: In static member function 'static void* QChar_from_python::convertible(PyObject*)':
/home/parallels/Coding/sire/wrapper/Qt/autoconvert_QChar.cpp:158:18: error: 'PyUnicode_GET_SIZE' was not declared in this scope; did you mean 'PyDict_GET_SIZE'?
  158 |              if (PyUnicode_GET_SIZE(obj_ptr) == 1){ return obj_ptr; }
      |                  ^~~~~~~~~~~~~~~~~~
      |                  PyDict_GET_SIZE
```

I'll work out a fix :-)

**Comment by chryswoods** [comment]
(for my reference - this page talks about the deprecated API single 3.12 - https://docs.python.org/3/c-api/unicode.html)
